---
# tasks file for jenkins
- name: install jdk
  yum: name=java-1.8.0-openjdk-devel state=installed

- name: download yum repository file of jenkins
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644

- name: import rpm key
  rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum: name=jenkins state=installed

- name: start jenkins
  service: name=jenkins state=started enabled=yes
